# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788606ea9f0586c5f24174e8ef89060420793d74ebf0deba3c6965a6838c64e147ec58ac3f65b20355a850d833239acfe08b4968b8d4193ddd7b0d551e1d1f78

test:
  secret_key_base: 1264540cd954952aff8b16391c31b79ff7bf5b8d67a97ffc6456e878cc21339986c4e1f7e77e8154d3900281318f344a0d7b9c51187fb3082508f805cc852a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
